FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
ARG Configuration=Release
ARG VAULT_TOKEN
ARG GITHUB_TOKEN
ENV HTDC_VAULT_TOKEN=$VAULT_TOKEN

WORKDIR /src

COPY . .

WORKDIR /src/HappyTravel.CurrencyConverter

RUN dotnet tool restore

CMD dotnet ef database update