FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
ARG Configuration=Release
ARG VAULT_TOKEN
ARG GITHUB_TOKEN
ENV HTDC_VAULT_TOKEN=$VAULT_TOKEN

WORKDIR /src

COPY . .

WORKDIR /src/HappyTravel.Tsutsujigasaki.Api

RUN dotnet tool restore

CMD dotnet ef database update