{{- $appPort := .Values.container.port -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
        - name: app
          image: {{ .Values.registry }}/tsutsujigasaki:{{ .Release.Namespace }}-{{ .Chart.Version }}
          ports:
            - containerPort: {{ $appPort }}
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: {{ $appPort }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 5
            httpGet:
              path: /health
              port: {{ $appPort }}
              scheme: HTTP
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-env
      imagePullSecrets:
      - name: travel-key-registry