{{- $svcPort := .Values.service.port -}}
{{- $appPort := .Values.container.port -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  ports:
    - port: {{ $svcPort }}
      targetPort: {{ $appPort }}
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}