env:
  ASPNETCORE_ENVIRONMENT: "Production"
  HTDC_VAULT_ENDPOINT: "https://vault.dev.happytravel.com/v1/"
  HTDC_TSUTSUJIGASAKI_SENTRY_ENDPOINT: "https://df89400a0d23436dbd54be0167bb021c@sentry.dev.happytravel.com/18"
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: "contour"
    contour.heptio.com/retry-on: "5xx"
    contour.heptio.com/num-retries: "5"
    contour.heptio.com/request-timeout: "15s"
    contour.heptio.com/per-try-timeout: "3000"
  hosts:
    - host: cc.dev.happytravel.com
      paths: [/]
  tls: 
    - hosts:
        - cc.dev.happytravel.com